version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
  aws-ecs: circleci/aws-ecs@1.2.0
  aws-cli: circleci/aws-cli@0.1.16
# 実行するjob
jobs:
  # buildするjob
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
  # testするjob
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up -d
          command: docker-compose up -d
      - run: sleep 10
      # バックエンド側のテスト
      - run:
          name: docker-compose run backend rails db:create RAILS_ENV=test
          command: docker-compose run backend rails db:create RAILS_ENV=test
      - run:
          name: docker-compose run backend rails db:migrate RAILS_ENV=test
          command: docker-compose run backend rails db:migrate RAILS_ENV=test
      - run:
          name: docker-compose run backend bundle exec rspec spec
          command: docker-compose run backend bundle exec rspec spec
      - run:
          name: Rubocop
          command:  docker-compose run backend bundle exec rubocop
      - run:
          name: docker-compose run frontend yarn install
          command: docker-compose run frontend yarn install
      # フロントエンド側のテスト
      - run:
          name: docker-compose run frontend yarn run test
          command: docker-compose run frontend yarn test
      - run:
          name: docker-compose down
          command: docker-compose down

# 順番を制御するworkflow
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build