version: 2.1
jobs:
  # buildするjob
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
  # testするjob
  test:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose up -d
          command: docker-compose up -d
      #- run: sleep 10
      # バックエンド側のテスト
      - run:
          name: docker-compose run backend --rm rails db:create RAILS_ENV=test
          command: docker-compose run backend --rm rails db:create RAILS_ENV=test
      - run:
          name: docker-compose run backend --rm rails db:migrate RAILS_ENV=test
          command: docker-compose run backend --rm rails db:migrate RAILS_ENV=test
      - run:
          name: docker-compose run backend --rm bundle exec rspec spec
          command: docker-compose run backend --rm bundle exec rspec spec
      - run:
          name: Rubocop
          command:  docker-compose run backend --rm bundle exec rubocop
      - run:
          name: docker-compose run frontend --rm yarn install
          command: docker-compose run frontend --rm yarn install
      # フロントエンド側のテスト
      - run:
          name: docker-compose run frontend --rm yarn run test
          command: docker-compose run front yarn test
      - run:
          name: docker-compose down
          command: docker-compose down